WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPConnectionPool(host='localhost', port=54689): Read timed out. (read timeout=120)")': /session/d389370dac3d9b1490f22c1e15623924/url
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPConnectionPool(host='localhost', port=54689): Read timed out. (read timeout=120)")': /session/d389370dac3d9b1490f22c1e15623924/url
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPConnectionPool(host='localhost', port=54689): Read timed out. (read timeout=120)")': /session/d389370dac3d9b1490f22c1e15623924/url