[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F565A2EBE0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/62213ba230bb73db6f0a62ce0d2451e2
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F565A2ECF0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/62213ba230bb73db6f0a62ce0d2451e2
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F565A2D150>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/62213ba230bb73db6f0a62ce0d2451e2