WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F19D67C9D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/4d60af94e96c499c7a24738faf664c35
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F19D67C640>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/4d60af94e96c499c7a24738faf664c35
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F19D828290>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/4d60af94e96c499c7a24738faf664c35