{"name": "test_authentication_correct_credentials", "status": "skipped", "statusDetails": {"message": "Skipped: Skipping test due to unexpected login error: InvalidSessionIdException", "trace": "('C:\\\\Users\\\\usmaan.arshad\\\\PycharmProjects\\\\PythonProject\\\\tests\\\\Authentication\\\\test_authentication_correct_credential.py', 45, 'Skipped: Skipping test due to unexpected login error: InvalidSessionIdException')"}, "attachments": [{"name": "log", "source": "d9c3823b-4513-48a4-b0da-a1759cc88104-attachment.txt", "type": "text/plain"}], "start": 1742964234800, "stop": 1742964372909, "uuid": "329a0ea8-1a72-4a88-a7a4-42c67801457a", "historyId": "7c5fdceb8be141e9360699da869202bf", "testCaseId": "7c5fdceb8be141e9360699da869202bf", "fullName": "tests.Authentication.test_authentication_correct_credential#test_authentication_correct_credentials", "labels": [{"name": "feature", "value": "Authentication - Correct Credentials"}, {"name": "story", "value": "Validate successful authentication with correct credentials for the Heroku."}, {"name": "severity", "value": "critical"}, {"name": "tag", "value": "test_demo"}, {"name": "tag", "value": "regression"}, {"name": "parentSuite", "value": "tests.Authentication"}, {"name": "suite", "value": "test_authentication_correct_credential"}, {"name": "host", "value": "RT-LT-597"}, {"name": "thread", "value": "6768-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.Authentication.test_authentication_correct_credential"}]}