WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPConnectionPool(host='localhost', port=63356): Read timed out. (read timeout=120)")': /session/c5a9374375ee0ddd1a6d115083e76e5e
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPConnectionPool(host='localhost', port=63356): Read timed out. (read timeout=120)")': /session/c5a9374375ee0ddd1a6d115083e76e5e
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPConnectionPool(host='localhost', port=63356): Read timed out. (read timeout=120)")': /session/c5a9374375ee0ddd1a6d115083e76e5e